export const ruLang = [
  './assets/klubok_en.png',
  './assets/hero_ru.webp',
  './assets/desktop/born.png',
  './assets/desktop/baptism.png',
  './assets/desktop/school_ru.webp',
  './assets/desktop/university.png',
  './assets/desktop/wedding.png',
  './assets/desktop/daughters_ru.png',
  './assets/desktop/work_ru.webp',
  './assets/desktop/grandson.webp',
  './assets/Develop ru.png',
  './assets/desktop/goldenwedding_ru.webp',
  './assets/desktop/twentynineteen.webp',
  './assets/navbook/milestones_ru.webp',
  './assets/navbook/stories_ru.webp',
  './assets/navbook/gallery_ru.webp',
  './assets/navbook/my_granny_ru.webp',
  './assets/navbook/remember_ru.webp',
  './assets/navbook/map_ru.webp',
  './assets/navbook/nanas_words_ru.webp',
];
export const enLang = [
  './assets/klubok_ru.png',
  './assets/hero_en.webp',
  './assets/desktop/born.png',
  './assets/desktop/baptism.png',
  './assets/desktop/school_en.webp',
  './assets/desktop/university.png',
  './assets/desktop/wedding.png',
  './assets/desktop/daughters_en.png',
  './assets/desktop/work_en.webp',
  './assets/desktop/grandson.webp',
  './assets/Develop eng.png',
  './assets/desktop/goldenwedding_en.webp',
  './assets/desktop/twentynineteen.webp',
  './assets/navbook/milestones_en.webp',
  './assets/navbook/stories_en.webp',
  './assets/navbook/gallery_en.webp',
  './assets/navbook/my_granny_en.webp',
  './assets/navbook/remember_en.webp',
  './assets/navbook/map_en.webp',
  './assets/navbook/nanas_words_en.webp',
];

export const ruLangMob = [
  './assets/klubok_en.png',
  './assets/mobile/hero_ru.webp',
  './assets/mobile/born_ru.webp',
  './assets/mobile/baptism_ru.webp',
  './assets/mobile/school_ru.webp',
  './assets/mobile/university_ru.webp',
  './assets/mobile/wedding_ru.webp',
  './assets/mobile/daughters_ru.webp',
  './assets/mobile/work_ru.webp',
  './assets/mobile/grandson_ru.png',
  './assets/Develop ru.png',
  './assets/mobile/goldenwedding_ru.webp',
  './assets/mobile/twentynineteen_ru.webp',
  './assets/navbook/milestones_ru.webp',
  './assets/navbook/stories_ru.webp',
  './assets/navbook/gallery_ru.webp',
  './assets/navbook/my_granny_ru.webp',
  './assets/navbook/remember_ru.webp',
  './assets/navbook/map_ru.webp',
  './assets/navbook/nanas_words_ru.webp',
];
export const enLangMob = [
  './assets/klubok_ru.png',
  './assets/mobile/hero_en.webp',
  './assets/mobile/born_en.webp',
  './assets/mobile/baptism_en.webp',
  './assets/mobile/school_en.webp',
  './assets/mobile/university_en.webp',
  './assets/mobile/wedding_en.webp',
  './assets/mobile/daughters_en.webp',
  './assets/mobile/work_en.webp',
  './assets/mobile/grandson_en.webp',
  './assets/Develop eng.png',
  './assets/mobile/goldenwedding_en.webp',
  './assets/mobile/twentynineteen_en.webp',
  './assets/navbook/milestones_en.webp',
  './assets/navbook/stories_en.webp',
  './assets/navbook/gallery_en.webp',
  './assets/navbook/my_granny_en.webp',
  './assets/navbook/remember_en.webp',
  './assets/navbook/map_en.webp',
  './assets/navbook/nanas_words_en.webp',
];

export const ruLangTab = [
  './assets/klubok_en.png',
  './assets/tablet/hero_ru.webp',
  './assets/tablet/born.png',
  './assets/tablet/baptism.png',
  './assets/tablet/school_ru.webp',
  './assets/tablet/university.png',
  './assets/tablet/wedding.png',
  './assets/tablet/daughters_ru.png',
  './assets/tablet/work_ru.webp',
  './assets/tablet/grandson.webp',
  './assets/Develop ru.png',
  './assets/tablet/goldenwedding_ru.webp',
  './assets/tablet/twentynineteen.webp',
  './assets/navbook/milestones_ru.webp',
  './assets/navbook/stories_ru.webp',
  './assets/navbook/gallery_ru.webp',
  './assets/navbook/my_granny_ru.webp',
  './assets/navbook/remember_ru.webp',
  './assets/navbook/map_ru.webp',
  './assets/navbook/nanas_words_ru.webp',
];
export const enLangTab = [
  './assets/klubok_ru.png',
  './assets/tablet/hero_en.webp',
  './assets/tablet/born.png',
  './assets/tablet/baptism.png',
  './assets/tablet/school_en.webp',
  './assets/tablet/university.png',
  './assets/tablet/wedding.png',
  './assets/tablet/daughters_en.png',
  './assets/tablet/work_en.webp',
  './assets/tablet/grandson.webp',
  './assets/Develop eng.png',
  './assets/tablet/goldenwedding_en.webp',
  './assets/tablet/twentynineteen.webp',
  './assets/navbook/milestones_en.webp',
  './assets/navbook/stories_en.webp',
  './assets/navbook/gallery_en.webp',
  './assets/navbook/my_granny_en.webp',
  './assets/navbook/remember_en.webp',
  './assets/navbook/map_en.webp',
  './assets/navbook/nanas_words_en.webp',
];

export const enText = [
  'Born in the village of Vlasovo, Moscow region in a family of poor peasants Tatyana Vasilievna and Yegor Fedorovich. <span class="paragraphSpacing">The father died in the war and the mother was left with four children in her arms, the youngest of whom was only one month old.</span>',
  'Baptism',
  'She was baptised in the Vlasov Church of the Intercession of the Most Holy Theotokos. <span class="paragraphSpacing">The church was of great importance not only in the life of Olga Yegorovna, but also in her parents, grandmother and all previous generations of the family.</span>',
  'School<br> years',
  'Work at the Chemical Plant in Roshal and study at the Roshal Chemical-Technological College in the evening department.<span class="paragraphSpacing">Education has always been the main thing for her and she was in no hurry to get married until she graduated from college.</span>',
  'She married a fellow villager Anatoly Sergeevich Shmelev.<br> After getting married, they moved to Moscow and got a job there.',
  'Birth of daughters',
  'Tatiana was born in 1961, Elena in 1967.<span class="paragraphSpacing">Elena was born with a pathology and Olga Yegorovna had to temporarily leave her job to take care of the sick child.</span><span class="paragraphSpacing"> In 1985, Elena died.</span>',
  'Work in the state secret Research Institute of Chemistry and Mechanics',
  '',
  'Birth of a<br> beloved<br> grandson',
  'Retirement',
  'Olga Yegorovna and Anatoly Sergeevich spent their retirement years in half in Moscow and in their native village of Vlasovo.<span class="paragraphSpacing">They were engaged in farming and raising a grandson who came every summer.</span>',
  'Golden<br> wedding',
  'After a long illness, she died at home surrounded by her close ones.',
];

export const ruText = [
  'Родилась в селе Власово, Московской области в семье простых крестьян Татьяны Васильевны и Егора Фёдоровича Семёновых. <span class="paragraphSpacing">Отец погиб на войне и мать осталась с четырьмя детьми на руках, младшему из которых был всего один месяц.</span>',
  'Крещение',
  'Была крещена во Власовской церкви Покрова Пресвятой Богородицы. <span class="paragraphSpacing">Храм имел большое значение не только в жизни Ольги Егоровны, но и её родителей, бабушки и всех предыдущих поколений семьи.</span>',
  'Школьные',
  'Работа на Химзаводе в Рошале и учёба в Рошальском Химико-Технологическом техникуме на вечернем отделении. <span class="paragraphSpacing">Образование всегда было главным для бабушки, и она не спешила замуж до окончания техникума.</span>',
  'Вышла замуж <br> за односельчанина Шмелёва Анатолия Сергеевича. <br> После женитьбы переехали в Москву и устроились на работу.',
  'Рождение<br> дочерей',
  'Татьяна 1961-го и Елена 1967-го годов рождения. <span class="paragraphSpacing">Леночка родилась нездоровой и Ольге Егоровне пришлось временно уйти с работы, чтобы ухаживать за больным ребёнком.</span>  <span class="paragraphSpacing">В 1985 году Леночки не стало.</span>',
  'Работа <br> в секретном НИИХМ',
  '(Научно-исследовательский институт химии и механики) ',
  'Рождение<br> любимого<br> внука',
  'Выход<br> на пенсию',
  'Свои пенсионные годы Ольга Егоровна и Анатолий Сергеевич проводили в Москве и в родном селе Власово. <span class="paragraphSpacing">Они занимались сельским хозяйством и воспитанием внука, который приезжал к ним каждое лето.</span>',
  'Золотая<br> свадьба',
  'После продолжительной болезни умерла дома в кругу родных.',
];

export const carouselImages = [
  './assets/carousel/carousel-1.jpg',
  './assets/carousel/carousel-2.jpg',
  './assets/carousel/carousel-3.jpg',
  './assets/carousel/carousel-4.jpg',
  './assets/carousel/carousel-5.jpg',
  './assets/carousel/carousel-6.jpg',
  './assets/carousel/carousel-7.jpg',
  './assets/carousel/carousel-8.jpg',
  './assets/carousel/carousel-9.jpg',
  './assets/carousel/carousel-10.jpg',
  './assets/carousel/carousel-11.webp',
  './assets/carousel/carousel-12.webp',
  './assets/carousel/carousel-13.webp',
  './assets/carousel/carousel-14.webp',
  './assets/carousel/carousel-15.webp',
  './assets/carousel/carousel-16.webp',
  './assets/carousel/carousel-17.webp',
];
